### ISSUE TITLE
MD is unable to dwell on application-private symbols

### ISSUE THREAD

**Issue by jhnphm** [nasa/MD#14]
**Checklist (Please check before submitting)**

* [ x] I reviewed the [Contributing Guide](https://github.com/nasa/MD/blob/main/CONTRIBUTING.md).
* [x ] I reviewed the [README file](https://github.com/nasa/MD/blob/main/README.md) to see if the feature is in the major future work.
* [x ] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
MD is unable to get application symbols, due to changes in cFE to make application symbols private: https://github.com/nasa/cFE/issues/952

**Describe the solution you'd like**
Using OS_ModuleSymbolLookup should be an option to peek/telemeter app-private symbols 

**Describe alternatives you've considered**
Leave as-is; implementation of  OS_ModuleSymbolLookup is the same as OS_SymbolLookup on vxWorks anyways, so it would appear this would only affect Linux. 

**Additional context**
https://github.com/nasa/MD/blob/408ff72c9ffa5001a11952df93e99d1bdccd576c/fsw/src/md_utils.c#L216

**Requester Info**
John Pham, Northrop Grumman

**Comment by skliper** [comment]
This should be already fixed on Linux, see https://github.com/nasa/osal/pull/1206.  The generic lookup will search both global and module symbol tables.

**Comment by jhnphm** [comment]
Ah, I missed that update. I'll close the ticket.
