### ISSUE TITLE
Deprecated #include of "cfe_platform_cfg.h"

### ISSUE THREAD

**Issue by chillfig** [nasa/MD#67]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/MD/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
The practice of #include "cfe_platform_cfg.h" has been deprecated. Applications should not be dependent on a specific CFE platform configuration

**To Reproduce**
Manually inspect

**Expected behavior**
Remove all `#include "cfe_platform_cfg.h"

**Code snips**
https://github.com/nasa/MD/blob/fe60ebcc04d1374d50ce81db1d99a395517daf89/fsw/src/md_verify.h#L28

**System observed on:**
N/A
 
**Additional context**
N/A

**Reporter Info**
Justin Figueroa, Vantage Systems

**Comment by thnkslprpt** [comment]
@chillfig
FYI Justin - also 1 case in the LC app

**Comment by chillfig** [comment]
> @chillfig FYI Justin - also 1 case in the LC app

Good catch. Thank you!

**Comment by chillfig** [comment]
Issue created for LC: https://github.com/nasa/LC/issues/108
